# Generated by Django 4.2.4 on 2023-09-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Recipename')),
                ('calories', models.CharField(max_length=64, verbose_name='CalorieValue')),
                ('fat', models.CharField(max_length=64, verbose_name='fat')),
                ('introduction', models.TextField(verbose_name='introduction')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='Username')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='BodyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=64, verbose_name='身高')),
                ('weight', models.CharField(max_length=64, verbose_name='体重')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='性别')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.userinfo')),
            ],
        ),
    ]
