# Generated by Django 4.2.4 on 2023-09-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_meals', to='meal.recipes')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_meals', to='meal.recipes')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_meals', to='meal.recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meal_plans', to='meal.userinfo', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('day1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday_meals', to='meal.dailymealplan')),
                ('day2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_meals', to='meal.dailymealplan')),
                ('day3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_meals', to='meal.dailymealplan')),
                ('day4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday_meals', to='meal.dailymealplan')),
                ('day5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday_meals', to='meal.dailymealplan')),
                ('day6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_meals', to='meal.dailymealplan')),
                ('day7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_meals', to='meal.dailymealplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_meal_plans', to='meal.userinfo', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='Month')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_meal_plans', to='meal.userinfo', verbose_name='User')),
                ('week1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_week_meals', to='meal.weeklymealplan')),
                ('week2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_week_meals', to='meal.weeklymealplan')),
                ('week3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_week_meals', to='meal.weeklymealplan')),
                ('week4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_week_meals', to='meal.weeklymealplan')),
                ('week5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_week_meals', to='meal.weeklymealplan')),
            ],
        ),
    ]
