# Generated by Django 4.2.4 on 2023-09-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_dailymealplan_weeklymealplan_monthlymealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyinfo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bodyinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_info', to='meal.userinfo'),
        ),
        migrations.RemoveField(
            model_name='dailymealplan',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='dailymealplan',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='dailymealplan',
            name='lunch',
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='breakfast',
            field=models.ManyToManyField(blank=True, related_name='breakfast_meals', to='meal.recipes'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='dinner_meals', to='meal.recipes'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch_meals', to='meal.recipes'),
        ),
    ]
