# Generated by Django 4.2.4 on 2023-09-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_remove_bodyinfo_user_id_bodyinfo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyinfo',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
    ]
