# Generated by Django 4.2.4 on 2023-09-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_bodyinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_info', to='meal.userinfo'),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='breakfast',
            field=models.ManyToManyField(blank=True, related_name='breakfast_meals', to='meal.recipes'),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='dinner_meals', to='meal.recipes'),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch_meals', to='meal.recipes'),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meal_plans', to='meal.userinfo', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='monthlymealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_meal_plans', to='meal.userinfo', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='monthlymealplan',
            name='week1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_week_meals', to='meal.weeklymealplan'),
        ),
        migrations.AlterField(
            model_name='monthlymealplan',
            name='week2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_week_meals', to='meal.weeklymealplan'),
        ),
        migrations.AlterField(
            model_name='monthlymealplan',
            name='week3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_week_meals', to='meal.weeklymealplan'),
        ),
        migrations.AlterField(
            model_name='monthlymealplan',
            name='week4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_week_meals', to='meal.weeklymealplan'),
        ),
        migrations.AlterField(
            model_name='monthlymealplan',
            name='week5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_week_meals', to='meal.weeklymealplan'),
        ),
        migrations.AlterField(
            model_name='weeklymealplan',
            name='day1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday_meals', to='meal.dailymealplan'),
        ),
        migrations.AlterField(
            model_name='weeklymealplan',
            name='day2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_meals', to='meal.dailymealplan'),
        ),
        migrations.AlterField(
            model_name='weeklymealplan',
            name='day3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_meals', to='meal.dailymealplan'),
        ),
        migrations.AlterField(
            model_name='weeklymealplan',
            name='day4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday_meals', to='meal.dailymealplan'),
        ),
        migrations.AlterField(
            model_name='weeklymealplan',
            name='day5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday_meals', to='meal.dailymealplan'),
        ),
        migrations.AlterField(
            model_name='weeklymealplan',
            name='day6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_meals', to='meal.dailymealplan'),
        ),
        migrations.AlterField(
            model_name='weeklymealplan',
            name='day7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_meals', to='meal.dailymealplan'),
        ),
        migrations.AlterField(
            model_name='weeklymealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_meal_plans', to='meal.userinfo', verbose_name='User'),
        ),
    ]
