# Generated by Django 4.2.4 on 2023-09-19 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='身高')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体重')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='BMI')),
                ('bodyfat', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Body Fat')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Recipename')),
                ('calories', models.CharField(max_length=64, verbose_name='CalorieValue')),
                ('fat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fat')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Protein')),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Carbohydrate')),
                ('introduction', models.TextField(verbose_name='introduction')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='Username')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('day1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday_meals', to='meal.dailymealplan')),
                ('day2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_meals', to='meal.dailymealplan')),
                ('day3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_meals', to='meal.dailymealplan')),
                ('day4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday_meals', to='meal.dailymealplan')),
                ('day5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday_meals', to='meal.dailymealplan')),
                ('day6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_meals', to='meal.dailymealplan')),
                ('day7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_meals', to='meal.dailymealplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_meal_plans', to='meal.userinfo', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='Month')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_meal_plans', to='meal.userinfo', verbose_name='User')),
                ('week1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_week_meals', to='meal.weeklymealplan')),
                ('week2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_week_meals', to='meal.weeklymealplan')),
                ('week3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_week_meals', to='meal.weeklymealplan')),
                ('week4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_week_meals', to='meal.weeklymealplan')),
                ('week5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_week_meals', to='meal.weeklymealplan')),
            ],
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='breakfast',
            field=models.ManyToManyField(blank=True, related_name='breakfast_meals', to='meal.recipes'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='dinner_meals', to='meal.recipes'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch_meals', to='meal.recipes'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meal_plans', to='meal.userinfo', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='BodyInfoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体重')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BMI')),
                ('bodyfat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Body Fat')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('body_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='meal.bodyinfo')),
            ],
        ),
        migrations.AddField(
            model_name='bodyinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_info', to='meal.userinfo'),
        ),
    ]
